# Generated by Django 5.0.4 on 2024-05-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('college_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('degree_name', models.CharField(max_length=100)),
                ('positions_of_responsibility', models.TextField()),
                ('gitHub', models.URLField()),
            ],
        ),
    ]
