# Generated by Django 5.0.4 on 2024-05-11 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobOperation', '0002_personaldata_job_seeker'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('stipend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_of_internship', models.CharField(max_length=100)),
                ('skills_required', models.CharField(max_length=200)),
                ('job_giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.jobseeker')),
            ],
        ),
    ]
