# Generated by Django 5.0.4 on 2024-05-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobOperation', '0004_alter_jobdata_job_giver'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.CharField(max_length=50)),
                ('terms_and_conditions', models.TextField()),
                ('top_companies', models.TextField()),
                ('app_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.admin')),
            ],
            options={
                'verbose_name_plural': 'Admin Content',
            },
        ),
    ]
