# Generated by Django 5.0.4 on 2024-05-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobOperation', '0005_admincontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobdata',
            options={'verbose_name_plural': 'Job Data'},
        ),
        migrations.AlterModelOptions(
            name='personaldata',
            options={'verbose_name_plural': 'Personal Data'},
        ),
        migrations.AlterField(
            model_name='admincontent',
            name='privacy_policy',
            field=models.TextField(),
        ),
    ]
